"""Constants for Stellar x402 mechanisms."""

from stellar_sdk import Network as StellarNetwork

# CAIP-2 network identifiers
STELLAR_PUBNET_CAIP2 = "stellar:pubnet"
STELLAR_TESTNET_CAIP2 = "stellar:testnet"

# Network passphrases
STELLAR_NETWORK_TO_PASSPHRASE = {
    STELLAR_PUBNET_CAIP2: StellarNetwork.PUBLIC_NETWORK_PASSPHRASE,
    STELLAR_TESTNET_CAIP2: StellarNetwork.TESTNET_NETWORK_PASSPHRASE,
}

# Default RPC URLs
DEFAULT_TESTNET_RPC_URL = "https://soroban-testnet.stellar.org"

# Stellar USDC addresses (SEP-41 Soroban contracts)
USDC_TESTNET_ADDRESS = "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA"
USDC_PUBNET_ADDRESS = "CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75"

# Default token decimals (Stellar USDC = 7)
DEFAULT_TOKEN_DECIMALS = 7

# Ledger timing
DEFAULT_ESTIMATED_LEDGER_SECONDS = 5
RPC_LEDGERS_SAMPLE_SIZE = 20

# Protocol
SUPPORTED_X402_VERSION = 2
DEFAULT_TIMEOUT_SECONDS = 60
DEFAULT_MAX_TRANSACTION_FEE_STROOPS = 50_000

# Address validation patterns
STELLAR_ASSET_ADDRESS_REGEX = r"^C[A-Z2-7]{55}$"
STELLAR_DESTINATION_ADDRESS_REGEX = r"^[GCM][A-Z2-7]{55}$"
